name: dlib
channels:
  - conda-forge
dependencies:
  - streamlit
  - dlib
  - numpy
  - scipy
  - opencv
  - face_recognition
  - streamlit-cropper==0.2.1
  - watchdog==2.1.9
  - plotly==5.9.0
  - matplotlib==3.7.1
  - mtcnn==0.1.1
  - tensorflow==2.9.1
  - pafy==0.5.5
  - youtube-dl==2020.12.2
  - scikit-image==0.20.0
  - torch==2.0.1
  - torchvision==0.13.0
  - facenet-pytorch==2.5.3
  - torchsummary==1.5.1
  - mmcv==2.0.0
  - timm==0.5.4
  - albumentations==1.2.0
  - iopath==0.1.10
  - simplejson==3.17.6
  - fvcore==0.1.5.post20220512